// There are going to be a few different types of contract builders that we will need to create
// 1. Contract Builder for the Energy Model (made for coding)
// 2. Contract Builder for the Login Screen (made for the user to create a new profile)
// 3. Contract Builder for the Profile Screen (made for the user to edit their profile)


export type ContractBuilderType = 'EnergyModelBuilder' | 'LoginScreenBuilder' | 'ProfileScreenBuilder';

interface EnergyModelBuilderType {
    attributes: EnergyModelAttributeType[];
}

type EnergyModelAttributeType = {
    questId: string;
    title: string;
    description: string;
    content: string;
    tags: string;
    AITools: string;
    Log: string;
    Metadata: string;
}

// this is the defaults for the contract builder as if it were a assisstant
export const defaultEnergyModel: EnergyModelBuilderType = {
    attributes: [
        {  
            // questID will be generated by the Hashing Algorithm
            questId: '0',
            // title will contain the quest's title
            title: 'Add a title',
            // description will contain the quest's description
            description: 'Description',
            // content will contain both the user's input and the AI Assistant's output
            content: 'Content',
            // tags will be automatically generated by the AI Assistant
            tags: 'Tags',
            // AITools will contain check boxes for the AI Assistant's tools
            AITools: 'AI Tools',
            // Log will contain the quest's log
            Log: 'Log',
            // Metadata will contain the quest's metadata (such as the quest's terms of service)
            Metadata: 'Metadata',
        },
    ],
};

export const defaultLoginModel: EnergyModelBuilderType = {
    attributes: [
        {
            questId: '0',
            // title will contain the profile's name
            title: 'Home #1',
            // description will contain the profile's bio
            description: 'Add a description',
            // content will contain more information about the user, such as their email, phone number, etc.
            content: 'Content',
            // tags will contain the profile's interests
            tags: 'Title',
            // AITools will contain the profile's AI Tools (such as the AI Assistant)
            AITools: 'AI Tools',
            // Log will contain the profile's log
            Log: 'Log',
            // Metadata will contain the profile's metadata (such as the profile's terms of service)
            Metadata: 'Metadata',
        },
    ],
};

export const defaultProfileModel: EnergyModelBuilderType = {
    attributes: [
        {
            questId: '0',
            title: 'Title',
            description: 'Description',
            content: 'Content',
            tags: 'Tags',
            AITools: 'AI Tools',
            Log: 'Log',
            Metadata: 'Metadata',
        },
    ],
};
